import { VerticalBox, Button, HorizontalBox } from "std-widgets.slint";
import { AppWindow } from "prac_template.slint";

export component MainWindow inherits Window {
    in property <string> sysName;
    in property <string> sysVer;
    in-out property <string> cpuUsage;
    in-out property <string> memUsage;
    property <int> count: 0;

    // width: 500px;
    // height: 400px;
    //background: transparent;
    HorizontalLayout {
        AppWindow { }
    }
}






































































// Button {
//     text: "Get name";
//     clicked => {
//         label.text = "OS: " + sysName;
//         label1.text = "Ver: " + sysVer;
//     }
// }

// HorizontalLayout {
//     Text {
//         text: cpuUsage;
//     }

//     Text {
//         text: memUsage;
//     }
// }

// VerticalLayout {
//     Rectangle {
//         background: white;
//         Text {
//             text: root.count;
//             color: black;
//         }

//         TouchArea {
//             clicked => {
//                 root.count += 1;
//             }
//         }
//     }
// }
