import { HorizontalBox, VerticalBox } from "std-widgets.slint";


component ProcessItem inherits Rectangle {
    in property <string> process-name: "Process";
    in property <string> cpu-usage: "0%";
    in property <string> memory: "0 MB";
    height: 55px;
    background: #1e293b;    //#1e293b     #915626
    border-radius: 10px;
    HorizontalBox {
        padding: 9px;
        spacing: 10px;
        alignment: start;
        Rectangle {
            width: 40px;
            height: 40px;
            background: #334155;
            border-radius: 10px;
            Text {
                text: "⚙";
                font-size: 20px;
                vertical-alignment: center;
                horizontal-alignment: center;
            }
        }

        VerticalBox {
            horizontal-stretch: 1;
            padding: 2px;
            spacing: -5px;
            Text {
                text: process-name;
                font-size: 15px;
                color: #f1f5f9;
                font-weight: 700;
            }

            HorizontalBox {
                spacing: 12px;
                Text {
                    text: "CPU: " + cpu-usage;
                    font-size: 12px;
                    color: #94a3b8;
                }

                Text {
                    text: "MEM: " + memory;
                    font-size: 12px;
                    color: #94a3b8;
                }
            }
        }
    }
}
